language: lisp
sudo: required

addons:
  apt:
    packages:
      - libc6-i386
      - openjdk-7-jre

env:
  matrix:
    - LISP=abcl
    - LISP=ccl-bin
    - LISP=sbcl-bin COVERALLS=true

install:
  - curl -L https://raw.githubusercontent.com/roswell/roswell/release/scripts/install-for-ci.sh | sh
  - git clone https://github.com/fukamachi/cl-coveralls ~/lisp/cl-coveralls

cache:
  directories:
    - $HOME/.roswell
    - $HOME/.config/common-lisp

script:
  - if [[ $LISP == 'sbcl-bin' ]];
    then
      ros -s cl-coveralls -s fiveam -s fast-io
          -e '(setf fiveam:*on-error* :backtrace
                    fiveam:*on-failure* :backtrace)'
          -e '(setf *debugger-hook*
                    (lambda (c h)
                      (declare (ignore c h))
                      (uiop:quit -1)))'
          -e '(pushnew :coverage *features*)'
          -e '(coveralls:with-coveralls (:exclude (list "t" "tools"))
                (asdf:test-system :fosc))';
    else
      ros -s fiveam -s fast-io -s usocket -s bordeaux-threads
          -e '(setf fiveam:*on-error* :backtrace
                    fiveam:*on-failure* :backtrace)'
          -e '(setf *debugger-hook*
                    (lambda (c h)
                      (declare (ignore c h))
                      (uiop:quit -1)))'
          -e '(asdf:test-system :fosc)';
    fi
