language: lisp
sudo: required

env:
  matrix:
    - LISP=sbcl-bin COVERALLS=true
    - LISP=ccl

install:
  - curl -L https://raw.githubusercontent.com/roswell/roswell/release/scripts/install-for-ci.sh | sh
  - git clone https://github.com/fukamachi/cl-coveralls ~/lisp/cl-coveralls

script:
  - ros -s cl-coveralls
        -s fiveam
        -s fast-io
        -s uiop
        -e '(setf fiveam:*debug-on-error* t
                  fiveam:*debug-on-failure* t)'
        -e '(setf *debugger-hook*
                  (lambda (c h)
                    (declare (ignore c h))
                    (uiop:quit -1)))'
        -e '(coveralls:with-coveralls (:exclude (list "t" "tools"))
                  (asdf:test-system :fosc))'
